/////////////////////////////////////////////////////////////////////////////////
// File : Source/FrontEnd/ResourceIDs.h
/////////////////////////////////////////////////////////////////////////////////
// Version : 0.1
// Status : Alpha
/////////////////////////////////////////////////////////////////////////////////
// Description : CCGOP GUI : Resource IDs
/////////////////////////////////////////////////////////////////////////////////
// Part of Scarab-Engine, licensed under the
// Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License
//   http://creativecommons.org/licenses/by-nc-nd/3.0/
/////////////////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////////////////
// Known Bugs : None.
/////////////////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////////////////
// Header prelude
#ifndef CCGOP_FRONTEND_RESOURCEIDS_H
#define CCGOP_FRONTEND_RESOURCEIDS_H

/////////////////////////////////////////////////////////////////////////////////
// Root Window
#define CCGOP_RESID_ROOT 1000

#define CCGOP_RESID_STATUSBAR         (CCGOP_RESID_ROOT + 0)
#define CCGOP_RESID_MAINMENU_TABS     (CCGOP_RESID_ROOT + 1)
#define CCGOP_RESID_MAINMENU_TABPANES (CCGOP_RESID_ROOT + 10) // CCGOP_MAINMENU_COUNT IDs

#define CCGOP_RESID_IMPORTEXPORT    (CCGOP_RESID_ROOT + 100)
#define CCGOP_RESID_HEROEXPLORER    (CCGOP_RESID_ROOT + 200)
#define CCGOP_RESID_RUNEEXPLORER    (CCGOP_RESID_ROOT + 300)
#define CCGOP_RESID_GEARSETEXPLORER (CCGOP_RESID_ROOT + 400)
#define CCGOP_RESID_OPTIMIZER       (CCGOP_RESID_ROOT + 500)

/////////////////////////////////////////////////////////////////////////////////
// Root/ImportExport
#define CCGOP_RESID_IMPORTEXPORT_LOADSAVE (CCGOP_RESID_IMPORTEXPORT + 0)

/////////////////////////////////////////////////////////////////////////////////
// Root/ImportExport/LoadSave
#define CCGOP_RESID_IMPORTEXPORT_LOADSAVE_GROUP    (CCGOP_RESID_IMPORTEXPORT_LOADSAVE + 0)
#define CCGOP_RESID_IMPORTEXPORT_LOADSAVE_FILENAME (CCGOP_RESID_IMPORTEXPORT_LOADSAVE + 1)
#define CCGOP_RESID_IMPORTEXPORT_LOADSAVE_LOAD     (CCGOP_RESID_IMPORTEXPORT_LOADSAVE + 2)
#define CCGOP_RESID_IMPORTEXPORT_LOADSAVE_SAVE     (CCGOP_RESID_IMPORTEXPORT_LOADSAVE + 3)

/////////////////////////////////////////////////////////////////////////////////
// Root/HeroExplorer
#define CCGOP_RESID_HEROEXPLORER_HEROTABLE    (CCGOP_RESID_HEROEXPLORER + 0)
#define CCGOP_RESID_HEROEXPLORER_HEROCREATION (CCGOP_RESID_HEROEXPLORER + 10)
#define CCGOP_RESID_HEROEXPLORER_HEROOPTIONS  (CCGOP_RESID_HEROEXPLORER + 20)

/////////////////////////////////////////////////////////////////////////////////
// Root/HeroExplorer/HeroTable
#define CCGOP_RESID_HEROEXPLORER_HEROTABLE_TABLE           (CCGOP_RESID_HEROEXPLORER_HEROTABLE + 0)
#define CCGOP_RESID_HEROEXPLORER_HEROTABLE_GROUP           (CCGOP_RESID_HEROEXPLORER_HEROTABLE + 1)
#define CCGOP_RESID_HEROEXPLORER_HEROTABLE_SELECTALL       (CCGOP_RESID_HEROEXPLORER_HEROTABLE + 2)
#define CCGOP_RESID_HEROEXPLORER_HEROTABLE_UNSELECTALL     (CCGOP_RESID_HEROEXPLORER_HEROTABLE + 3)
#define CCGOP_RESID_HEROEXPLORER_HEROTABLE_CHECKALL        (CCGOP_RESID_HEROEXPLORER_HEROTABLE + 4)
#define CCGOP_RESID_HEROEXPLORER_HEROTABLE_UNCHECKALL      (CCGOP_RESID_HEROEXPLORER_HEROTABLE + 5)
#define CCGOP_RESID_HEROEXPLORER_HEROTABLE_CHECKSELECTED   (CCGOP_RESID_HEROEXPLORER_HEROTABLE + 6)
#define CCGOP_RESID_HEROEXPLORER_HEROTABLE_UNCHECKSELECTED (CCGOP_RESID_HEROEXPLORER_HEROTABLE + 7)

/////////////////////////////////////////////////////////////////////////////////
// Root/HeroExplorer/HeroCreation
#define CCGOP_RESID_HEROEXPLORER_HEROCREATION_GROUP    (CCGOP_RESID_HEROEXPLORER_HEROCREATION + 0)
#define CCGOP_RESID_HEROEXPLORER_HEROCREATION_NAME     (CCGOP_RESID_HEROEXPLORER_HEROCREATION + 1)
#define CCGOP_RESID_HEROEXPLORER_HEROCREATION_RANK     (CCGOP_RESID_HEROEXPLORER_HEROCREATION + 2)
#define CCGOP_RESID_HEROEXPLORER_HEROCREATION_LEVEL    (CCGOP_RESID_HEROEXPLORER_HEROCREATION + 3)
#define CCGOP_RESID_HEROEXPLORER_HEROCREATION_EVOLVED  (CCGOP_RESID_HEROEXPLORER_HEROCREATION + 4)
#define CCGOP_RESID_HEROEXPLORER_HEROCREATION_SANCTIFY (CCGOP_RESID_HEROEXPLORER_HEROCREATION + 5)
#define CCGOP_RESID_HEROEXPLORER_HEROCREATION_CREATE   (CCGOP_RESID_HEROEXPLORER_HEROCREATION + 6)

/////////////////////////////////////////////////////////////////////////////////
// Root/HeroExplorer/HeroOptions
#define CCGOP_RESID_HEROEXPLORER_HEROOPTIONS_GROUP          (CCGOP_RESID_HEROEXPLORER_HEROOPTIONS + 0)
#define CCGOP_RESID_HEROEXPLORER_HEROOPTIONS_MAXRANK        (CCGOP_RESID_HEROEXPLORER_HEROOPTIONS + 1)
#define CCGOP_RESID_HEROEXPLORER_HEROOPTIONS_MAXLEVEL       (CCGOP_RESID_HEROEXPLORER_HEROOPTIONS + 2)
#define CCGOP_RESID_HEROEXPLORER_HEROOPTIONS_EVOLVED        (CCGOP_RESID_HEROEXPLORER_HEROOPTIONS + 3)
#define CCGOP_RESID_HEROEXPLORER_HEROOPTIONS_SANCTIFYCHOICE (CCGOP_RESID_HEROEXPLORER_HEROOPTIONS + 4)
#define CCGOP_RESID_HEROEXPLORER_HEROOPTIONS_SANCTIFY       (CCGOP_RESID_HEROEXPLORER_HEROOPTIONS + 5)
#define CCGOP_RESID_HEROEXPLORER_HEROOPTIONS_DELETE         (CCGOP_RESID_HEROEXPLORER_HEROOPTIONS + 6)

/////////////////////////////////////////////////////////////////////////////////
// Root/RuneExplorer
#define CCGOP_RESID_RUNEEXPLORER_RUNETABLE    (CCGOP_RESID_RUNEEXPLORER + 0)
#define CCGOP_RESID_RUNEEXPLORER_RUNECREATION (CCGOP_RESID_RUNEEXPLORER + 10)
#define CCGOP_RESID_RUNEEXPLORER_RUNEOPTIONS  (CCGOP_RESID_RUNEEXPLORER + 30)
#define CCGOP_RESID_RUNEEXPLORER_RUNESEARCH   (CCGOP_RESID_RUNEEXPLORER + 40)

/////////////////////////////////////////////////////////////////////////////////
// Root/RuneExplorer/RuneTable
#define CCGOP_RESID_RUNEEXPLORER_RUNETABLE_TABLE           (CCGOP_RESID_RUNEEXPLORER_RUNETABLE + 0)
#define CCGOP_RESID_RUNEEXPLORER_RUNETABLE_GROUP           (CCGOP_RESID_RUNEEXPLORER_RUNETABLE + 1)
#define CCGOP_RESID_RUNEEXPLORER_RUNETABLE_SELECTALL       (CCGOP_RESID_RUNEEXPLORER_RUNETABLE + 2)
#define CCGOP_RESID_RUNEEXPLORER_RUNETABLE_UNSELECTALL     (CCGOP_RESID_RUNEEXPLORER_RUNETABLE + 3)
#define CCGOP_RESID_RUNEEXPLORER_RUNETABLE_CHECKALL        (CCGOP_RESID_RUNEEXPLORER_RUNETABLE + 4)
#define CCGOP_RESID_RUNEEXPLORER_RUNETABLE_UNCHECKALL      (CCGOP_RESID_RUNEEXPLORER_RUNETABLE + 5)
#define CCGOP_RESID_RUNEEXPLORER_RUNETABLE_CHECKSELECTED   (CCGOP_RESID_RUNEEXPLORER_RUNETABLE + 6)
#define CCGOP_RESID_RUNEEXPLORER_RUNETABLE_UNCHECKSELECTED (CCGOP_RESID_RUNEEXPLORER_RUNETABLE + 7)

/////////////////////////////////////////////////////////////////////////////////
// Root/RuneExplorer/RuneCreation
#define CCGOP_RESID_RUNEEXPLORER_RUNECREATION_GROUP           (CCGOP_RESID_RUNEEXPLORER_RUNECREATION + 0)
#define CCGOP_RESID_RUNEEXPLORER_RUNECREATION_SLOT            (CCGOP_RESID_RUNEEXPLORER_RUNECREATION + 1)
#define CCGOP_RESID_RUNEEXPLORER_RUNECREATION_SET             (CCGOP_RESID_RUNEEXPLORER_RUNECREATION + 2)
#define CCGOP_RESID_RUNEEXPLORER_RUNECREATION_RANK            (CCGOP_RESID_RUNEEXPLORER_RUNECREATION + 3)
#define CCGOP_RESID_RUNEEXPLORER_RUNECREATION_QUALITY         (CCGOP_RESID_RUNEEXPLORER_RUNECREATION + 4)
#define CCGOP_RESID_RUNEEXPLORER_RUNECREATION_LEVEL           (CCGOP_RESID_RUNEEXPLORER_RUNECREATION + 5)
#define CCGOP_RESID_RUNEEXPLORER_RUNECREATION_MAINSTAT        (CCGOP_RESID_RUNEEXPLORER_RUNECREATION + 6)
#define CCGOP_RESID_RUNEEXPLORER_RUNECREATION_INNATESTAT      (CCGOP_RESID_RUNEEXPLORER_RUNECREATION + 7)
#define CCGOP_RESID_RUNEEXPLORER_RUNECREATION_INNATESTATVALUE (CCGOP_RESID_RUNEEXPLORER_RUNECREATION + 8)
#define CCGOP_RESID_RUNEEXPLORER_RUNECREATION_RANDOMSTAT      (CCGOP_RESID_RUNEEXPLORER_RUNECREATION + 9)
#define CCGOP_RESID_RUNEEXPLORER_RUNECREATION_RANDOMSTATVALUE (CCGOP_RESID_RUNEEXPLORER_RUNECREATION + 10)
#define CCGOP_RESID_RUNEEXPLORER_RUNECREATION_CREATE          (CCGOP_RESID_RUNEEXPLORER_RUNECREATION + 11)

/////////////////////////////////////////////////////////////////////////////////
// Root/RuneExplorer/RuneOptions
#define CCGOP_RESID_RUNEEXPLORER_RUNEOPTIONS_GROUP  (CCGOP_RESID_RUNEEXPLORER_RUNEOPTIONS + 0)
#define CCGOP_RESID_RUNEEXPLORER_RUNEOPTIONS_LOCK   (CCGOP_RESID_RUNEEXPLORER_RUNEOPTIONS + 1)
#define CCGOP_RESID_RUNEEXPLORER_RUNEOPTIONS_POOL   (CCGOP_RESID_RUNEEXPLORER_RUNEOPTIONS + 2)
#define CCGOP_RESID_RUNEEXPLORER_RUNEOPTIONS_DELETE (CCGOP_RESID_RUNEEXPLORER_RUNEOPTIONS + 3)

/////////////////////////////////////////////////////////////////////////////////
// Root/RuneExplorer/RuneSearch
#define CCGOP_RESID_RUNEEXPLORER_RUNESEARCH_GROUP        (CCGOP_RESID_RUNEEXPLORER_RUNESEARCH + 0)
#define CCGOP_RESID_RUNEEXPLORER_RUNESEARCH_SLOT         (CCGOP_RESID_RUNEEXPLORER_RUNESEARCH + 1)
#define CCGOP_RESID_RUNEEXPLORER_RUNESEARCH_SET          (CCGOP_RESID_RUNEEXPLORER_RUNESEARCH + 2)
#define CCGOP_RESID_RUNEEXPLORER_RUNESEARCH_RANK         (CCGOP_RESID_RUNEEXPLORER_RUNESEARCH + 3)
#define CCGOP_RESID_RUNEEXPLORER_RUNESEARCH_QUALITY      (CCGOP_RESID_RUNEEXPLORER_RUNESEARCH + 4)
#define CCGOP_RESID_RUNEEXPLORER_RUNESEARCH_LEVEL        (CCGOP_RESID_RUNEEXPLORER_RUNESEARCH + 5)
#define CCGOP_RESID_RUNEEXPLORER_RUNESEARCH_MAINSTAT     (CCGOP_RESID_RUNEEXPLORER_RUNESEARCH + 6)
#define CCGOP_RESID_RUNEEXPLORER_RUNESEARCH_SUBSTATSMODE (CCGOP_RESID_RUNEEXPLORER_RUNESEARCH + 7)
#define CCGOP_RESID_RUNEEXPLORER_RUNESEARCH_SUBSTAT      (CCGOP_RESID_RUNEEXPLORER_RUNESEARCH + 8)
#define CCGOP_RESID_RUNEEXPLORER_RUNESEARCH_SUBSTATVALUE (CCGOP_RESID_RUNEEXPLORER_RUNESEARCH + 9)
#define CCGOP_RESID_RUNEEXPLORER_RUNESEARCH_INDICATOR    (CCGOP_RESID_RUNEEXPLORER_RUNESEARCH + 10)
#define CCGOP_RESID_RUNEEXPLORER_RUNESEARCH_CLEAR        (CCGOP_RESID_RUNEEXPLORER_RUNESEARCH + 11)
#define CCGOP_RESID_RUNEEXPLORER_RUNESEARCH_APPLY        (CCGOP_RESID_RUNEEXPLORER_RUNESEARCH + 12)

/////////////////////////////////////////////////////////////////////////////////
// Root/GearSetExplorer
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETTABLE    (CCGOP_RESID_GEARSETEXPLORER + 0)
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETDETAILS  (CCGOP_RESID_GEARSETEXPLORER + 10)
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETSTATS    (CCGOP_RESID_GEARSETEXPLORER + 20)
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETCREATION (CCGOP_RESID_GEARSETEXPLORER + 30)
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETOPTIONS  (CCGOP_RESID_GEARSETEXPLORER + 40)
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETBUILD    (CCGOP_RESID_GEARSETEXPLORER + 50)

/////////////////////////////////////////////////////////////////////////////////
// Root/GearSetExplorer/GearSetTable
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETTABLE_TABLE           (CCGOP_RESID_GEARSETEXPLORER_GEARSETTABLE + 0)
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETTABLE_GROUP           (CCGOP_RESID_GEARSETEXPLORER_GEARSETTABLE + 1)
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETTABLE_SELECTALL       (CCGOP_RESID_GEARSETEXPLORER_GEARSETTABLE + 2)
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETTABLE_UNSELECTALL     (CCGOP_RESID_GEARSETEXPLORER_GEARSETTABLE + 3)
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETTABLE_CHECKALL        (CCGOP_RESID_GEARSETEXPLORER_GEARSETTABLE + 4)
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETTABLE_UNCHECKALL      (CCGOP_RESID_GEARSETEXPLORER_GEARSETTABLE + 5)
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETTABLE_CHECKSELECTED   (CCGOP_RESID_GEARSETEXPLORER_GEARSETTABLE + 6)
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETTABLE_UNCHECKSELECTED (CCGOP_RESID_GEARSETEXPLORER_GEARSETTABLE + 7)

/////////////////////////////////////////////////////////////////////////////////
// Root/GearSetExplorer/GearSetDetails
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETDETAILS_GROUP      (CCGOP_RESID_GEARSETEXPLORER_GEARSETDETAILS + 0)
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETDETAILS_SLOTGROUP  (CCGOP_RESID_GEARSETEXPLORER_GEARSETDETAILS + 1)
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETDETAILS_HEADLINE   (CCGOP_RESID_GEARSETEXPLORER_GEARSETDETAILS + 2)
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETDETAILS_MAINSTAT   (CCGOP_RESID_GEARSETEXPLORER_GEARSETDETAILS + 3)
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETDETAILS_INNATESTAT (CCGOP_RESID_GEARSETEXPLORER_GEARSETDETAILS + 4)
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETDETAILS_RANDOMSTAT (CCGOP_RESID_GEARSETEXPLORER_GEARSETDETAILS + 5)
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETDETAILS_LOCK       (CCGOP_RESID_GEARSETEXPLORER_GEARSETDETAILS + 6)
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETDETAILS_UNEQUIP    (CCGOP_RESID_GEARSETEXPLORER_GEARSETDETAILS + 7)

/////////////////////////////////////////////////////////////////////////////////
// Root/GearSetExplorer/GearSetStats
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETSTATS_GROUP    (CCGOP_RESID_GEARSETEXPLORER_GEARSETSTATS + 0)
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETSTATS_LABEL    (CCGOP_RESID_GEARSETEXPLORER_GEARSETSTATS + 1)
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETSTATS_VALUE    (CCGOP_RESID_GEARSETEXPLORER_GEARSETSTATS + 2)
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETSTATS_SETBONUS (CCGOP_RESID_GEARSETEXPLORER_GEARSETSTATS + 3)
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETSTATS_MODE     (CCGOP_RESID_GEARSETEXPLORER_GEARSETSTATS + 4)
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETSTATS_HEROVIEW (CCGOP_RESID_GEARSETEXPLORER_GEARSETSTATS + 5)

/////////////////////////////////////////////////////////////////////////////////
// Root/GearSetExplorer/GearSetCreation
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETCREATION_GROUP  (CCGOP_RESID_GEARSETEXPLORER_GEARSETCREATION + 0)
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETCREATION_NAME   (CCGOP_RESID_GEARSETEXPLORER_GEARSETCREATION + 1)
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETCREATION_CREATE (CCGOP_RESID_GEARSETEXPLORER_GEARSETCREATION + 2)

/////////////////////////////////////////////////////////////////////////////////
// Root/GearSetExplorer/GearSetOptions
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETOPTIONS_GROUP   (CCGOP_RESID_GEARSETEXPLORER_GEARSETOPTIONS + 0)
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETOPTIONS_NAME    (CCGOP_RESID_GEARSETEXPLORER_GEARSETOPTIONS + 1)
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETOPTIONS_RENAME  (CCGOP_RESID_GEARSETEXPLORER_GEARSETOPTIONS + 2)
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETOPTIONS_CLONE   (CCGOP_RESID_GEARSETEXPLORER_GEARSETOPTIONS + 3)
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETOPTIONS_LOCK    (CCGOP_RESID_GEARSETEXPLORER_GEARSETOPTIONS + 4)
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETOPTIONS_UNEQUIP (CCGOP_RESID_GEARSETEXPLORER_GEARSETOPTIONS + 5)
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETOPTIONS_DELETE  (CCGOP_RESID_GEARSETEXPLORER_GEARSETOPTIONS + 6)

/////////////////////////////////////////////////////////////////////////////////
// Root/GearSetExplorer/GearSetBuild
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETBUILD_GROUP      (CCGOP_RESID_GEARSETEXPLORER_GEARSETBUILD + 0)
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETBUILD_SLOTGROUP  (CCGOP_RESID_GEARSETEXPLORER_GEARSETBUILD + 1)
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETBUILD_HEADLINE   (CCGOP_RESID_GEARSETEXPLORER_GEARSETBUILD + 2)
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETBUILD_MAINSTAT   (CCGOP_RESID_GEARSETEXPLORER_GEARSETBUILD + 3)
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETBUILD_INNATESTAT (CCGOP_RESID_GEARSETEXPLORER_GEARSETBUILD + 4)
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETBUILD_RANDOMSTAT (CCGOP_RESID_GEARSETEXPLORER_GEARSETBUILD + 5)
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETBUILD_RUNE       (CCGOP_RESID_GEARSETEXPLORER_GEARSETBUILD + 6)
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETBUILD_RUNEREMOVE (CCGOP_RESID_GEARSETEXPLORER_GEARSETBUILD + 7)
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETBUILD_RUNEEQUIP  (CCGOP_RESID_GEARSETEXPLORER_GEARSETBUILD + 8)
#define CCGOP_RESID_GEARSETEXPLORER_GEARSETBUILD_CLEARPOOLS (CCGOP_RESID_GEARSETEXPLORER_GEARSETBUILD + 9)

/////////////////////////////////////////////////////////////////////////////////
// Root/Optimizer
#define CCGOP_RESID_OPTIMIZER_OPTIMIZEROPTIONS (CCGOP_RESID_OPTIMIZER + 0)

/////////////////////////////////////////////////////////////////////////////////
// Root/Optimizer/OptimizerOptions
#define CCGOP_RESID_OPTIMIZER_OPTIMIZEROPTIONS_GROUP (CCGOP_RESID_OPTIMIZER_OPTIMIZEROPTIONS + 0)

/////////////////////////////////////////////////////////////////////////////////
// Header end
#endif // CCGOP_FRONTEND_RESOURCEIDS_H

